name: Create and Publish a Container Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t app:latest .

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Devguard Scanner
        run: |
          curl -L https://github.com/l3montree-dev/devguard/releases/latest/download/devguard-scanner-linux-amd64.tar.gz | tar xz &&
          mv devguard-scanner-linux-amd64 /usr/local/bin/devguard-scanner

      - name: Generate SBOM of Image
        run: |
          syft app:latest -o cyclonedx-json > /tmp/sbom.json

      - name: Upload SBOM to Devguard
        run: |
          devguard-scanner sbom /tmp/sbom.json --token "{{ DEVGUARD_PAT }}" --apiUrl "https://api.guard.dev.aivot.cloud" --assetName "aivot/prosuna/prosuna-identity-provider"
