name: Create and Publish a Container Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t app:latest .

      - name: Install syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM of Image
        run: |
          syft app:latest -o spdx-json > sbom.spdx.json &&
          syft app:latest -o cyclonedx-xml > sbom.cyclonedx.xml
